config/routes.rb
Mpate::Application.routes.draw do

  get "settings/index"
  
  get 'competitors/badges' => 'competitors#badges', as: 'badges'
  get 'teams/setup' => 'teams#setup', as: 'setup_teams'
  post 'teams/assign_room' => 'teams#assign_room', as: 'assign_room'
  post 'settings/save_all' => 'settings#save_all', as: 'save_all_settings'

  delete 'competitors/reset' => 'competitors#reset', as: 'reset_competitors'
  delete 'leaders/reset' => 'leaders#reset', as: 'reset_leaders'
  delete 'schools/reset' => 'schools#reset', as: 'reset_schools'
  delete 'tasks/reset' => 'tasks#reset', as: 'reset_tasks'
  delete 'teams/reset' => 'teams#reset', as: 'reset_teams'
  delete 'volunteers/reset' => 'volunteers#reset', as: 'reset_volunteers'

  resources :competitors
  resources :teams
  resources :managers
  resources :tasks
  resources :volunteers
  resources :leaders
  resources :schools
  resources :sessions
  resources :settings

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  get 'results' => 'teams#results'

  root "main#index"

end

app/models/task.rb
class Task < ActiveRecord::Base

	# Each task can be assigned to multiple volunteers
	
	has_many :volunteers

	# Set up data validation for our forms

  	validates :name, presence: true

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  require 'csv'
  include Resetter

	# Set up the different controllers, so we can 
	# call them when we need to do specific actions

	# Default page shows current tasks in alphabetical order
	def index
		@tasks=Task.all.order("name ASC")

	    respond_to do |format|
	      format.html
	      format.csv do
	        filename = "mpate-" + params[:controller] + "-" + Time.now.strftime("%m-%e-%Y")
	        headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
	        headers['Content-Type'] ||= 'text/csv'
	      end
	    end
	end

	# Display form to fill out when we want to create a new task
	def new
		@task=Task.new
	end

	# If new task form successfully filled out, add new task and return to task listing
	# Otherwise redisplay form to get corrections
	def create
		@task=Task.new(model_params)
		if @task.save
			redirect_to tasks_path
		else
			render :new
		end
	end

	# Display correct information when we want to see data of specific task
	def show
		@task = Task.find(params[:id])
	end

	# Prepopulate editing form
	def edit
		@task = Task.find(params[:id])
	end

	# If editing form correct, update the task and return to task listing
	# Otherwise, return to form for corrections
	def update
		@task = Task.find(params[:id])
		if @task.update(model_params)
			redirect_to tasks_path
		else
			render :edit
		end
	end

	# Delete correct record when we want to remove a task from database
	def destroy
		@task = Task.find(params[:id])
		@task.destroy
		redirect_to tasks_path
	end

	# List the only information allowed to be passed, to aid in security

	def model_params
		params.require(:task).permit(
		  :name
		)
	end
end

app/views/tasks/_form.html.erb
<%= form_for @task do |f| %>
	<!-- If page was reloaded due to errors, display errors -->
	<% if @task.errors.any? %>
		<div id="errors">
			<h5>Something Went Wrong</h5>
			<ul>
				<% @task.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- Display for fields for data entry, prepopulated if data already exists -->
	<div>
		<%=f.label :name %>
		<%=f.text_field:name %>
	</div>

	<!-- If task is already created, we're saving changes
		otherwise it would be a new task and we need to add the record -->	
	<% if @task.id %>
		<%= f.submit "Save Changes" %>
	<% else %>
		<%= f.submit "Add Task" %>
	<% end %>


<%end%>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<!-- Display the form created in _form.html.erb -->

<%= render 'form' %>

app/views/tasks/index.csv.erb
<!-- Table downloaded as CSV when system manager archives data -->
<% headers = [
	'Task Name'
] %>

<%= CSV.generate_line headers %>
<% @tasks.each do |task| %><%= CSV.generate_line([
  	task.name,
]) %><% end %>

app/views/tasks/index.html.erb
<h1>Tasks
<%= link_to "Add a Task", new_task_path, class: "btn btn-new" %>
</h1>
<!-- List the current tasks in the database -->
<table border="0" cellspacing="0" cellpadding="0">
  <thead>
    <tr>
      <th width="60%">Name</th>
      <th width="10%">Assigned</th>
      <th width="30%">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= (task.volunteers.count > 0) ? "Yes" : "No" %></td>
        <td><%= link_to "Edit", edit_task_path(task), class: "btn btn-edit" %> <%= link_to "Delete", task_path(task), method: :delete, confirm: "Are you sure?", class: "btn btn-delete" %></td>
      </tr>
    <%end%>
  </tbody>
</table>
<br>
<!-- Manager is the only one able to download the archive csv, or to reset the database table -->
<% if is_manager? %>
  <%= link_to "Download as CSV", tasks_path(format: "csv"), class: "btn" %>
  <%= link_to "Reset Tasks", reset_tasks_path, method: :delete, confirm: "Are you sure?", class: "btn btn-delete" %>
<% end %>

app/views/tasks/new.html.erb
<h2>New Task</h2>

<!-- Display the form created in _form.html.erb -->

<%= render 'form' %>