config/routes.rb
Mpate::Application.routes.draw do

  get "settings/index"
  
  get 'competitors/badges' => 'competitors#badges', as: 'badges'
  get 'teams/setup' => 'teams#setup', as: 'setup_teams'
  post 'teams/assign_room' => 'teams#assign_room', as: 'assign_room'
  post 'settings/save_all' => 'settings#save_all', as: 'save_all_settings'

  delete 'competitors/reset' => 'competitors#reset', as: 'reset_competitors'
  delete 'leaders/reset' => 'leaders#reset', as: 'reset_leaders'
  delete 'schools/reset' => 'schools#reset', as: 'reset_schools'
  delete 'tasks/reset' => 'tasks#reset', as: 'reset_tasks'
  delete 'teams/reset' => 'teams#reset', as: 'reset_teams'
  delete 'volunteers/reset' => 'volunteers#reset', as: 'reset_volunteers'

  resources :competitors
  resources :teams
  resources :managers
  resources :tasks
  resources :volunteers
  resources :leaders
  resources :schools
  resources :sessions
  resources :settings

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  get 'results' => 'teams#results'

  root "main#index"

end

app/models/competitor.rb
class Competitor < ActiveRecord::Base

	# Each competitor can be a student of a school 
	# as well as a member of a team

	belongs_to :school
	belongs_to :team

	# Set up data validation for our forms

	validates_presence_of :school
	validates :first_name, presence: true
	validates :last_name, presence: true
	validates :email, allow_blank: true, email: true, uniqueness: true
 	validates :grade, presence: true
 	validates :address_line_1, presence: true
 	validates :city, presence: true
 	validates :state, presence: true
 	validates :zip, presence: true

 	# This creates a way to display both names with a single variable
 	
	def full_name
		first_name + " " + last_name
	end

end

app/controllers/competitors_controller.rb
class CompetitorsController < ApplicationController
  require 'csv'
  include Resetter

  # Ensure schools and teams are referenced as we display the competitors data
  before_action :set_schools_and_teams, except: [:index, :show, :destroy]

  # Set up the different controllers, so we can 
  # call them when we need to do specific actions

  # Main index page for competitors, which lists them alphabetically by first name
	def index
		@competitors=Competitor.all.order("first_name ASC, last_name ASC")

    respond_to do |format|
      format.html do
        # If logged in as user, then it displays the list of competitors
        # If not, then we got here through open signup, and display thanks for signing up
        if is_logged_in?
          render "competitors/index"
        else
          render "competitors/thanks"
        end
      end
      format.csv do
        filename = "mpate-" + params[:controller] + "-" + Time.now.strftime("%m-%e-%Y")
        headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
	end

  # Add another controller method to render the badges CSV file for download.

  def badges
    @competitors=Competitor.all
    respond_to do |format|
      format.csv do
        filename = "competitor-badges-" + Time.now.strftime("%m-%e-%Y")
        headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  # Renders the form for new competitors
	def new
		@competitor=Competitor.new
	end

  # If logged in as school, go directly to specific school infomation page
  # Otherwise we show the total list of competitors as only other way to see this page is to be 
  # logged in as a manager
  # This redirect is if form correctly filled out. If not, then we return to the form

	def create
		@competitor=Competitor.new(model_params)
		if @competitor.save
      if is_school?
        redirect_to school_path(session[:user])
      else
  			redirect_to competitors_path
      end
		else
			render :new
		end
	end

  # Used to find the information of a specific competitor when we want to see his information
  def show
    @competitor = Competitor.find(params[:id])
  end

  # Find the information of a specific competitor, so we can fill out the fields on the form when we go to edit
  def edit
    @competitor = Competitor.find(params[:id])
  end

  # If we got a successful form filled out, update the competitor. Otherwise, redirect to the form again
  def update
    @competitor = Competitor.find(params[:id])
    if @competitor.update(model_params)
      redirect_to competitor_path(@competitor)
    else
      render :edit
    end
  end

  # Find the correct competitor and remove from database (Called when we delete a record)
  def destroy
  	@competitor = Competitor.find(params[:id])
  	@competitor.destroy
  	redirect_to competitors_path
  end

  # This will find and display schools and teams in ascending order
  def set_schools_and_teams
    @schools = School.all.order(school_name: :asc)
    @teams = Team.all.order(:color, :number)
  end


  # List the only information allowed to be passed, to aid in security

	def model_params
		params.require(:competitor).permit(
      		:first_name,
      		:last_name,
      		:address_line_1,
      		:address_line_2,
      		:city,
      		:state,
      		:zip,
      		:grade,
      		:email,
          :school_id,
          :team_id
 			)
	end

end

app/views/competitors/_form.html.erb
<!-- Set up the form for competitor data entry -->

<%= form_for @competitor do |f| %>
	<!-- If page was reloaded due to errors, display errors -->
	<% if @competitor.errors.any? %>
		<div id="errors">
			<h5>Something Went Wrong</h5>
			<ul>
				<% @competitor.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- If this page was accessed with school level security
		then the school the student belongs to will be set automatically -->
	<% if is_school? %>
		<%= f.hidden_field :school_id, value: session[:user] %>
	<% else %>
		<!-- If this page was not accessed with school level security
			then we used manager level, and manager can manually set school -->
		<div>
			<%= f.label :school_id, "School" %>
			<%= collection_select(:competitor, :school_id, @schools, :id, :school_name, prompt: "Select A School") %> 
		</div>
	<% end %>
	<div>
		<%=f.label :first_name %>
		<%=f.text_field :first_name %>
	</div>
	<div>
		<%=f.label :last_name %>
		<%=f.text_field :last_name %>
	</div>
	<div>
		<%=f.label :address_line_1 %>
		<%=f.text_field :address_line_1 %>
	</div>
	<div>
		<%=f.label :address_line_2 %>
		<%=f.text_field :address_line_2 %>
	</div>
	<div>
		<%=f.label :city %>
		<%=f.text_field :city %>
	</div>
	<div>
		<%=f.label :state %>
		<%=f.text_field :state %>
	</div>
	<div>
		<%=f.label :zip %>
		<%=f.number_field :zip %>
	</div>
	<div>
		<%=f.label :grade %>
		<label>
			<%=f.radio_button :grade, "junior" %>
			Junior
		</label>
		<label>
			<%=f.radio_button :grade, "senior" %>
			Senior
		</label>
	</div>
	<div>
		<%=f.label :email %>
		<%=f.email_field :email %>
	</div>

	<!-- Manager can edit the team the student belongs to -->
	<% if is_manager? %>
		<div>
			<%= f.label :team_id, "Team" %>
			<%= collection_select(:competitor, :team_id, @teams, :id, :team_name, prompt: "Select A Team") %> 
		</div>
	<% end %>

	<!-- If competitor is already created, we're saving changes
		otherwise it would be a new competitor and we need to add the record -->	
	<% if @competitor.id %>
		<%= f.submit "Save Changes" %>
	<% else %>
		<%= f.submit "Add Competitor" %>
	<% end %>
<%end%>

app/views/competitors/badges.csv.erb
<!-- Set up the tables for downloading badge data -->
<% headers = [
	'First Name',
	'Last Name',
	'School',
	'Team Number',
	'Team Color'
] %>

<%= CSV.generate_line headers %>
<% @competitors.each do |competitor| %>
<% 
	if competitor.team.nil?
    	team_number = "n/a"
		team_color = "n/a"
	else
		team_number = competitor.team.number
		team_color = competitor.team.color
	end
%><%= CSV.generate_line([
  	competitor.first_name,
  	competitor.last_name,
  	competitor.school.school_name,
  	team_number,
  	team_color
]) %><% end %>

app/views/competitors/edit.html.erb
<h1>Edit Competitor</h1>

<!-- Display the form created in _form.html.erb -->

<%= render 'form' %>

app/views/competitors/index.csv.erb
<!-- Table downloaded as CSV to archive competitors -->
<% headers = [
	'First Name',
	'Last Name',
	'Email',
	'School',
	'Grade',
	'Address Line 1',
	'Address Line 2',
	'City',
	'State',
	'Zip Code',
	'Team'
] %>

<%= CSV.generate_line headers %>
<% @competitors.each do |competitor| %>
<% 
	if competitor.team.nil?
		team_name = "unassigned"
	else
		team_name = competitor.team.team_name
	end
%><%= CSV.generate_line([
  	competitor.first_name,
  	competitor.last_name,
  	competitor.email,
  	competitor.school.school_name,
  	competitor.grade,
  	competitor.address_line_1,
  	competitor.address_line_2,
  	competitor.city,
  	competitor.state,
  	competitor.zip,
  	team_name
]) %><% end %>

app/views/competitors/index.html.erb
<h1>Competitors
<%= link_to "Add a Competitor", new_competitor_path, class: "btn btn-new" %>
</h1>

<!-- Create a table to list the competitors -->

<table border="0" cellspacing="0" cellpadding="0">
  <thead>
    <tr>
      <th width="20%">Competitor Name</th>
      <th width="25%">School</th>
      <th width="25%">Team</th>
      <th width="30%">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
  	<% @competitors.each do |competitor| %>
      <tr>
    		<td><%= competitor.full_name %></td>
        <td><%= (competitor.school) ? competitor.school.school_name : "Not assigned" %></td>
        <td><%= (competitor.team) ? competitor.team.team_name : "Not Assigned" %></td>
        <td><%= link_to "Show", competitor_path(competitor), class: "btn btn-show" %> <%= link_to "Edit", edit_competitor_path(competitor), class: "btn btn-edit" %>  <%= link_to "Delete", competitor_path(competitor), method: :delete, confirm: "Are you sure?", class: "btn btn-delete" %></td>
      </tr>
  	<%end%>
  </tbody>
</table>
<br>
<!-- Manager is the only one able to download the archive csv, or to reset the database table -->
<% if is_manager? %>
  <%= link_to "Download as CSV", competitors_path(format: "csv"), class: "btn" %>
  <%= link_to "Download Badge CSV", badges_path(format: "csv"), class: "btn" %>
  <%= link_to "Reset Competitors", reset_competitors_path, method: :delete, confirm: "Are you sure?", class: "btn btn-delete" %>
<% end %>

app/views/competitors/new.html.erb
<h2>Add a Competitor</h2>

<!-- Display the form created in _form.html.erb -->

<%= render 'form' %>

app/views/competitors/show.html.erb
<h1><%= @competitor.full_name %> <% if is_manager? %><%= link_to "Edit", edit_competitor_path(@competitor), class: "btn btn-edit" %><% end %></h1>

<!-- Display competitor information -->

<table border="0" cellspacing="0" cellpadding="3" class="alt">
	<tr><th>First Name:</th><td><%= @competitor.first_name %></td></tr>
	<tr><th>Last Name:</th><td><%= @competitor.last_name %></td></tr>
	<tr><th>Address Line 1:</th><td><%= @competitor.address_line_1 %></td></tr>
	<tr><th>Address Line 2:</th><td><%= @competitor.address_line_2 %></td></tr>
	<tr><th>City:</th><td><%= @competitor.city %></td></tr>
	<tr><th>State:</th><td><%= @competitor.state %></td></tr>
	<tr><th>Zip Code:</th><td><%= @competitor.zip %></td></tr>
	<tr><th>Grade:</th><td><%= @competitor.grade %></td></tr>
	<tr><th>Email:</th><td><%= @competitor.email %></td></tr>
	<tr><th>School:</th><td><%= (@competitor.school) ? @competitor.school.school_name : 'Not Assigned' %></td></tr>
	<tr><th>Team:</th><td><%= (@competitor.team) ? @competitor.team.team_name : 'Not Assigned' %></td></tr>
</table>

app/views/competitors/thanks.html.erb
<!-- This is the thank you page displayed when competitors have signed up -->
<h1>Thanks for registering for MPATE!</h1>