config/routes.rb
Mpate::Application.routes.draw do

  get "settings/index"
  
  get 'competitors/badges' => 'competitors#badges', as: 'badges'
  get 'teams/setup' => 'teams#setup', as: 'setup_teams'
  post 'teams/assign_room' => 'teams#assign_room', as: 'assign_room'
  post 'settings/save_all' => 'settings#save_all', as: 'save_all_settings'

  delete 'competitors/reset' => 'competitors#reset', as: 'reset_competitors'
  delete 'leaders/reset' => 'leaders#reset', as: 'reset_leaders'
  delete 'schools/reset' => 'schools#reset', as: 'reset_schools'
  delete 'tasks/reset' => 'tasks#reset', as: 'reset_tasks'
  delete 'teams/reset' => 'teams#reset', as: 'reset_teams'
  delete 'volunteers/reset' => 'volunteers#reset', as: 'reset_volunteers'

  resources :competitors
  resources :teams
  resources :managers
  resources :tasks
  resources :volunteers
  resources :leaders
  resources :schools
  resources :sessions
  resources :settings

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  get 'results' => 'teams#results'

  root "main#index"

end

app/models/school.rb
class School < ActiveRecord::Base

	# Each school will have several students
	
	has_many :competitors, dependent: :destroy

	# Set up data validation for our forms
  # Only require username and password if the system manager requires schools to log in

 	validates :user_name, presence: true, uniqueness: true, if: :school_password_required
  validates :password, presence: true, length: { minimum: 4, maximum: 64}, if: :school_password_required
  validates :school_name, presence: true
  validates :address_line_1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zip, presence: true

  # This checks if the schools need to log in to sign up competitors, or if it's open sign up
  def school_password_required
    Setting.find_by(key: "require_school_password").value == "yes"
  end
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  require 'csv'
  include Resetter

  # Set up the different controllers, so we can 
  # call them when we need to do specific actions

  # Default display will list all schools in ascending order
  def index
  	@schools = School.all.order("school_name ASC")

    respond_to do |format|
      format.html do
        # If school is logged in, we render the main page.
        # Otherwise, they were not logged in, then school signed up on open page. Display thanks for signing up
        if is_logged_in?
          render "schools/index"
        else
          render "schools/thanks"
        end
      end
      format.csv do
        filename = "mpate-" + params[:controller] + "-" + Time.now.strftime("%m-%e-%Y")
        headers['Content-Disposition'] = "attachment; filename=\"#{filename}\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  # Display form for new school to sign up
  def new
  	@school = School.new
  end

  # If new school signup form has valid information, add to database and re-render page
  # Otherwise, redisplay form so we can get corrections
  def create
  	@school = School.new(model_params)
  	if @school.save
  		redirect_to schools_path
  	else
  		render :new
  	end
  end

  # Show correct information when we want to see data on a specific school
  def show
    @school = School.find(params[:id])
  end

  # Prepopulate editing form when we want to make changes to school data
  def edit
    @school = School.find(params[:id])
  end

  # If editing is successful, save changes and return to main page
  # Otherwise, return to form to get corrections
  def update
    @school = School.find(params[:id])
    if @school.update(model_params)
      redirect_to school_path(@school)
    else
      render :edit
    end
  end

  # Ensure we delete correct school when we want to remove it from database
  def destroy
  	@school = School.find(params[:id])
  	@school.destroy
  	redirect_to schools_path
  end

  # List the only information allowed to be passed, to aid in security

  def model_params
  	params.require(:school).permit(
  		:school_name,
  		:user_name,
  		:password,
  		:address_line_1,
  		:address_line_2,
  		:city,
  		:state,
  		:zip,
  		:phone,
  		:teachers_attending
  	)
  end
end

app/views/schools/_form.html.erb
<%= form_for @school do |f| %>
	<!-- If page was reloaded due to errors, display errors -->
	<% if @school.errors.any? %>
		<div id="errors">
			<h5>Something Went Wrong</h5>
			<ul>
				<% @school.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- Display for fields for data entry, prepopulated if data already exists -->
	<% if require_school_password? %>
		<div>
			<%= f.label :user_name %>
			<%= f.text_field :user_name %>
		</div>
		<div>
			<%= f.label :password %>
			<%= f.text_field :password %>
		</div>
	<% end %>
	<div>
		<%= f.label :school_name %>
		<%= f.text_field :school_name %>
	</div>
	<div>
		<%= f.label :address_line_1 %>
		<%= f.text_field :address_line_1 %>
	</div>
	<div>
		<%= f.label :address_line_2 %>
		<%= f.text_field :address_line_2 %>
	</div>
	<div>
		<%= f.label :city %>
		<%= f.text_field :city %>
	</div>
	<div>
		<%= f.label :state %>
		<%= f.text_field :state %>
	</div>
	<div>
		<%= f.label :zip %>
		<%= f.number_field :zip %>
	</div>
	<div>
		<%= f.label :phone %>
		<%= f.text_field :phone %>
	</div>
	<div>
		<%= f.label :teachers_attending %>
		<%= f.text_field :teachers_attending %>
	</div>

	<!-- If school is already created, we're saving changes
		otherwise it would be a new school and we need to add the record -->	
	<% if @school.id %>
		<%= f.submit "Save Changes" %>
	<% else %>
		<%= f.submit "Add School" %>
	<% end %>
<% end %>

app/views/schools/edit.html.erb
<h1>Edit School</h1>

<!-- Display the form created in _form.html.erb -->

<%= render 'form' %>

app/views/schools/index.csv.erb
<!-- Table downloaded as CSV when system manager archives data -->
<% headers = [
	'User Name',
	'School Name',
	'Address Line 1',
	'Address Line 2',
	'City',
	'State',
	'Zip Code'
] %>

<%= CSV.generate_line headers %>
<% @schools.each do |school| %><%= CSV.generate_line([
  	school.user_name,
  	school.school_name,
  	school.address_line_1,
  	school.address_line_2,
  	school.city,
  	school.state,
  	school.zip,
]) %><% end %>

app/views/schools/index.html.erb
<h1>All Schools
<%= link_to "Add a school", new_school_path, class: "btn btn-new" %>
</h1>
<!-- List the current schools in the database -->

<table border="0" cellspacing="0" cellpadding="0">
  <thead>
    <tr>
      <th width="60%">Name</th>
      <th width="10%">Students</th>
      <th width="30%">&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @schools.each do |school| %>
      <tr>
        <td><%= school.school_name %></td>
        <td><%= school.competitors.count %></td>
        <td>
          <%= link_to "Show", school_path(school), class: "btn btn-show" %>
          <%= link_to "Edit", edit_school_path(school), class: "btn btn-edit" %>
          <%= link_to "Delete", school_path(school), method: :delete, confirm: "Are you sure?", class: "btn btn-delete" %>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>
<br>
<!-- Manager is the only one able to download the archive csv, or to reset the database table -->
<% if is_manager? %>
  <%= link_to "Download as CSV", schools_path(format: "csv"), class: "btn" %>
  <%= link_to "Reset Schools", reset_schools_path, method: :delete, confirm: "Are you sure?\nThis will also delete all competitors for this school.", class: "btn btn-delete" %>
<% end %>

app/views/schools/new.html.erb
<h2>New School</h2>

<!-- Display the form created in _form.html.erb -->

<%= render 'form' %>

app/views/schools/show.html.erb
<h1><%= @school.school_name %> <%= link_to "Edit", edit_school_path(@school), class: "btn btn-edit" %></h1>

<!-- Display school information -->
<table border="0" cellspacing="0" cellpadding="3" class="alt">
	<tr><th>School Name:</th><td><%= @school.school_name %></td></tr>
	<% if require_school_password? %>
		<tr><th>Username:</th><td><%= @school.user_name %></td></tr>
		<tr><th>Password:</th><td><%= @school.password %></td></tr>
	<% end %>
	<tr><th>Address Line 1:</th><td><%= @school.address_line_1 %></td></tr>
	<tr><th>Address Line 2:</th><td><%= @school.address_line_2 %></td></tr>
	<tr><th>City:</th><td><%= @school.city %></td></tr>
	<tr><th>State:</th><td><%= @school.state %></td></tr>
	<tr><th>Zip Code:</th><td><%= @school.zip %></td></tr>
	<tr><th>Phone Number:</th><td><%= @school.phone %></td></tr>
	<tr><th>Teachers Attending:</th><td><%= @school.teachers_attending %></td></tr>
</table>
<hr>
<!-- Display competitors that belong to this school -->
<h5>
	Students From This School
	<%= link_to "Add Competitor", new_competitor_path, class: "btn btn-new" %>
</h5> 
<table border="0" cellspacing="0" cellpadding="0">
	<thead>
    	<tr>
      		<th width="50%">Name</th>
      		<th width="20%">Team</th>
      		<th width="30%">&nbsp;</th>
    	</tr>
  	</thead>
  	<tbody>
		<% @school.competitors.each do |competitor| %>
	  		<tr>
		  		<td><%= competitor.full_name %></td>
		  		<td><%= (competitor.team) ? competitor.team.team_name : 'Not Assigned' %></td>
		  		<td>
		  			<%= link_to "Show", competitor_path(competitor), class: "btn btn-show" %>
		  			<!-- Only managers can edit and delete competitors -->
			        <% if is_manager? %>
			  			<%= link_to "Edit", edit_competitor_path(competitor), class: "btn btn-edit" %>
			  			<%= link_to "Delete", competitor_path(competitor), method: :delete, confirm: "Are you sure?", class: "btn btn-delete" %>
			  		<% end %>
		  		</td>
	  		</tr>
		<% end %>
  	</tbody>
</table>

app/views/schools/thanks.html.erb
<!-- Page displayed when schools sign up -->
<h1>Thanks for registering your school!</h1>
<p>Your students may now register by following the "Competitor Signup" link.</p>