config/routes.rb
Mpate::Application.routes.draw do

  get "settings/index"
  
  get 'competitors/badges' => 'competitors#badges', as: 'badges'
  get 'teams/setup' => 'teams#setup', as: 'setup_teams'
  post 'teams/assign_room' => 'teams#assign_room', as: 'assign_room'
  post 'settings/save_all' => 'settings#save_all', as: 'save_all_settings'

  delete 'competitors/reset' => 'competitors#reset', as: 'reset_competitors'
  delete 'leaders/reset' => 'leaders#reset', as: 'reset_leaders'
  delete 'schools/reset' => 'schools#reset', as: 'reset_schools'
  delete 'tasks/reset' => 'tasks#reset', as: 'reset_tasks'
  delete 'teams/reset' => 'teams#reset', as: 'reset_teams'
  delete 'volunteers/reset' => 'volunteers#reset', as: 'reset_volunteers'

  resources :competitors
  resources :teams
  resources :managers
  resources :tasks
  resources :volunteers
  resources :leaders
  resources :schools
  resources :sessions
  resources :settings

  get 'login' => 'sessions#new'
  get 'logout' => 'sessions#destroy'

  get 'results' => 'teams#results'

  root "main#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mpate</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <header>
    <!-- Create the header of the page to display navigation options
      which are only displayed to appropriate security levels -->
    <h1><%= link_to "MPATE", root_path %></h1>
    <nav>
      <ul>
        <% if is_logged_in? %>
          <% if is_manager? %>
            <li><%= link_to "Competitors", competitors_path %></li>
            <li><%= link_to "Leaders", leaders_path %></li>
            <li><%= link_to "Managers", managers_path %></li>
            <li><%= link_to "Schools", schools_path %></li>
          <% end %>
          <% if is_manager? || is_taskmaster? %>
            <li><%= link_to "Tasks", tasks_path %></li>
          <% end %>
          <% if is_manager? || is_leader? %>
            <li><%= link_to "Teams", teams_path %></li>
          <% end %>
          <% if is_manager? || is_taskmaster? %>
            <li><%= link_to "Volunteers", volunteers_path %></li>
          <% end %>
          <% if is_manager? %>
            <li><%= link_to "Results", results_path %></li>
            <li><%= link_to "Settings", settings_path %></li>
          <% end %>
          <li><%= link_to "Log Out", logout_path %></li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
          <% if !require_school_password? && is_online? %>
            <li><%= link_to "School Signup", new_school_path %></li>
            <li><%= link_to "Competitor Signup", new_competitor_path %></li>
          <% end %>
          <% if is_online? %>
            <li><%= link_to "Volunteer Signup", new_volunteer_path %></li>
          <% end %>
        <% end %>
      </ul>
    </nav>
  </header>
  <div id="main">
    <% flash.each do |name, msg| %>
      <div class="flash-<%=name%>"><%=msg%></div>
    <% end %>
    <%= yield %>
    <% unless is_online? %>
      <br>
      <p class="align-center">The system is currently offline.</p>
    <% end %>
  </div>
  <footer>
    <%= link_to "Home", root_path %>
  </footer>
</body>
</html>